server:
  port: 8081

spring:
  application:
    name: fraud

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microServices?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
