spring:
  application:
    name: eureka-server


  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microServices
    username: root
    password: 1234

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false





